<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.opencart.test</groupId>
  <artifactId>SeleniumOpenCartLab</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <dependencies>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>4.21.0</version>
    </dependency>
  </dependencies>
</project>